# Generated by Django 5.0 on 2026-02-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0006_setup_user_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Etiket Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('color', models.CharField(choices=[('blue', 'Mavi'), ('green', 'Yeşil'), ('red', 'Kırmızı'), ('yellow', 'Sarı'), ('purple', 'Mor'), ('pink', 'Pembe'), ('orange', 'Turuncu'), ('teal', 'Turkuaz')], default='blue', max_length=20, verbose_name='Renk')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'Etiket',
                'verbose_name_plural': 'Etiketler',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='corpus.tag', verbose_name='Etiketler'),
        ),
    ]
