# Generated by Django 5.0 on 2026-02-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0015_corpusmetadata_sentence_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, help_text='5 başarısız denemeden sonra 30 dakika kilitlenir', null=True, verbose_name='Hesap Kilitli (Süre)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Token 24 saat geçerlidir', null=True, verbose_name='Token Geçerlilik Süresi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Doğrulama Emaili Gönderilme Zamanı'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_token',
            field=models.CharField(blank=True, help_text='Email doğrulama için benzersiz token', max_length=64, null=True, unique=True, verbose_name='Email Doğrulama Token'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Kullanıcı email adresini doğruladı mı?', verbose_name='Email Doğrulandı'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='failed_login_attempts',
            field=models.IntegerField(default=0, verbose_name='Başarısız Giriş Denemeleri'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Başarısız Giriş'),
        ),
    ]
