# Generated by Django 5.0 on 2026-02-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0016_userprofile_account_locked_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_expires_at',
            field=models.DateTimeField(blank=True, help_text='Token 1 saat geçerlidir', null=True, verbose_name='Reset Token Geçerlilik Süresi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sıfırlama Emaili Gönderilme Zamanı'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_token',
            field=models.CharField(blank=True, help_text='Şifre sıfırlama için benzersiz token', max_length=64, null=True, unique=True, verbose_name='Şifre Sıfırlama Token'),
        ),
    ]
