# Generated by Django 5.0 on 2026-02-11 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0018_add_owner_to_collection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempted', models.CharField(help_text='Girilen username/email', max_length=150, verbose_name='Denenen Kullanıcı Adı')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Giriş Zamanı')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Adresi')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device bilgisi', verbose_name='User Agent')),
                ('success', models.BooleanField(db_index=True, default=True, verbose_name='Başarılı mı?')),
                ('failure_reason', models.CharField(blank=True, help_text='Örn: invalid_credentials, account_locked, email_not_verified', max_length=200, verbose_name='Başarısızlık Nedeni')),
                ('session_key', models.CharField(blank=True, help_text='Django session key (başarılı login için)', max_length=40, verbose_name='Session Key')),
                ('is_suspicious', models.BooleanField(db_index=True, default=False, help_text='Otomatik tespit edilen şüpheli aktivite', verbose_name='Şüpheli Aktivite')),
                ('device_type', models.CharField(blank=True, help_text='Desktop, Mobile, Tablet, Bot', max_length=50, verbose_name='Cihaz Tipi')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Tarayıcı')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='İşletim Sistemi')),
                ('location_city', models.CharField(blank=True, max_length=100, verbose_name='Şehir')),
                ('location_country', models.CharField(blank=True, max_length=100, verbose_name='Ülke')),
                ('user', models.ForeignKey(blank=True, help_text='Null ise başarısız login attempt (user bulunamadı)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Login Geçmişi',
                'verbose_name_plural': 'Login Geçmişi Kayıtları',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'user'], name='corpus_logi_timesta_2b8234_idx'), models.Index(fields=['ip_address', '-timestamp'], name='corpus_logi_ip_addr_9c9743_idx'), models.Index(fields=['is_suspicious', '-timestamp'], name='corpus_logi_is_susp_32ac9f_idx')],
            },
        ),
    ]
