# Generated by Django 5.0 on 2026-02-12 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0019_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportlog',
            name='document_title',
            field=models.CharField(blank=True, help_text='Belge silinse bile adını saklar', max_length=255, verbose_name='Doküman Adı (Snapshot)'),
        ),
        migrations.AlterField(
            model_name='content',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='corpus.document', verbose_name='Doküman'),
        ),
    ]
