# Generated by Django 5.0 on 2026-02-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0020_exportlog_document_title_alter_content_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enable_watermark',
            field=models.BooleanField(default=True, help_text='Export edilen dosyalarda CorpusLIO atıf bilgisi gösterilsin mi?', verbose_name="Export'larda Filigran Ekle"),
        ),
    ]
