# Generated by Django 5.0 on 2026-02-04 12:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Dosya Adı')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Dosya')),
                ('format', models.CharField(max_length=10, verbose_name='Format')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yüklenme Tarihi')),
                ('processed', models.BooleanField(default=False, verbose_name='İşlendi mi?')),
            ],
            options={
                'verbose_name': 'Belge',
                'verbose_name_plural': 'Belgeler',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True, verbose_name='Ham Metin')),
                ('cleaned_text', models.TextField(blank=True, verbose_name='Temiz Metin')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='corpus.document', verbose_name='Belge')),
            ],
            options={
                'verbose_name': 'İçerik',
                'verbose_name_plural': 'İçerikler',
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=list, verbose_name='Analiz Verisi')),
                ('analyzed_at', models.DateTimeField(auto_now=True, verbose_name='Analiz Tarihi')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='corpus.document', verbose_name='Belge')),
            ],
            options={
                'verbose_name': 'Analiz',
                'verbose_name_plural': 'Analizler',
            },
        ),
        migrations.CreateModel(
            name='ProcessingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True, verbose_name='Görev ID')),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('PROCESSING', 'İşleniyor'), ('COMPLETED', 'Tamamlandı'), ('FAILED', 'Başarısız')], default='PENDING', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata Mesajı')),
                ('progress', models.IntegerField(default=0, verbose_name='İlerleme %')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='corpus.document', verbose_name='Belge')),
            ],
            options={
                'verbose_name': 'İşlem Görevi',
                'verbose_name_plural': 'İşlem Görevleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
