# Generated by Django 5.0 on 2026-02-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Yazar, tarih, kaynak, tür vb. bilgiler', verbose_name='Metadata'),
        ),
    ]
