# Generated by Django 5.0 on 2026-02-04 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_document_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Koleksiyon Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('documents', models.ManyToManyField(related_name='collections', to='corpus.document', verbose_name='Belgeler')),
            ],
            options={
                'verbose_name': 'Koleksiyon',
                'verbose_name_plural': 'Koleksiyonlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=500, verbose_name='Sorgu')),
                ('query_type', models.CharField(choices=[('kwic', 'KWIC'), ('ngram', 'N-gram'), ('advanced', 'Advanced')], default='kwic', max_length=20, verbose_name='Sorgu Tipi')),
                ('parameters', models.JSONField(default=dict, verbose_name='Parametreler')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favori mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.document', verbose_name='Belge')),
            ],
            options={
                'verbose_name': 'Sorgu Geçmişi',
                'verbose_name_plural': 'Sorgu Geçmişleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
