# Generated by Django 5.0 on 2026-02-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_collection_queryhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='processed',
        ),
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.CharField(blank=True, max_length=255, verbose_name='Yazar'),
        ),
        migrations.AddField(
            model_name='document',
            name='genre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tür'),
        ),
        migrations.AddField(
            model_name='document',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('PRE', 'Okul Öncesi'), ('1', '1. Sınıf'), ('2', '2. Sınıf'), ('3', '3. Sınıf'), ('4', '4. Sınıf'), ('5', '5. Sınıf'), ('6', '6. Sınıf'), ('7', '7. Sınıf'), ('8', '8. Sınıf'), ('9', '9. Sınıf'), ('10', '10. Sınıf'), ('11', '11. Sınıf'), ('12', '12. Sınıf'), ('UNI', 'Üniversite/Akademik'), ('GEN', 'Genel/Yetişkin')], max_length=10, null=True, verbose_name='Sınıf Seviyesi'),
        ),
        migrations.AddField(
            model_name='document',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='document',
            name='language',
            field=models.CharField(default='tr', max_length=10, verbose_name='Dil'),
        ),
        migrations.AddField(
            model_name='document',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Basım Yılı'),
        ),
        migrations.AddField(
            model_name='document',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, verbose_name='Yayınevi'),
        ),
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.CharField(blank=True, max_length=255, verbose_name='Kaynak'),
        ),
        migrations.AddField(
            model_name='document',
            name='subject',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ders/Alan'),
        ),
        migrations.AlterField(
            model_name='document',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Diğer detaylar (JSON)', verbose_name='Ek Metadata'),
        ),
    ]
