# Generated by Django 5.0 on 2026-02-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0004_remove_document_processed_document_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='İşlendi mi?'),
        ),
    ]
