# Generated by Django 5.0 on 2026-02-04 16:02

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    
    # 1. Student (End User)
    student, _ = Group.objects.get_or_create(name='Student')
    # Students have only basic read access (handled via view logic, typically no specific model perms needed if basic auth is used)
    
    # 2. Academician (Power User)
    academician, _ = Group.objects.get_or_create(name='Academician')
    # Grant permissions if needed, e.g. add_document
    # For now we handle this via view decorators, but groups must exist.
    
    # 3. Developer (Admin)
    developer, _ = Group.objects.get_or_create(name='Developer') 
    
def remove_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Student', 'Academician', 'Developer']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0005_document_processed'),
        ('auth', '0012_alter_user_first_name_max_length'), # Ensure auth dependency
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups),
    ]
