# Generated by Django 5.0 on 2026-02-04 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0007_tag_document_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500, verbose_name='Arama Sorgusu')),
                ('search_type', models.CharField(choices=[('basic', 'Basit'), ('fuzzy', 'Benzer'), ('regex', 'Regex'), ('advanced', 'Gelişmiş')], default='basic', max_length=20, verbose_name='Arama Tipi')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='Filtreler')),
                ('result_count', models.IntegerField(default=0, verbose_name='Sonuç Sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Arama Geçmişi',
                'verbose_name_plural': 'Arama Geçmişleri',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='corpus_sear_user_id_8e045d_idx')],
            },
        ),
    ]
