# Generated by Django 5.0 on 2026-02-06 22:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0008_searchhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('anonymous', 'Anonim Kullanıcı'), ('registered', 'Kayıtlı Kullanıcı'), ('verified', 'Doğrulanmış Araştırmacı'), ('developer', 'Geliştirici (API Erişimi)'), ('admin', 'Sistem Yöneticisi')], default='registered', max_length=20, verbose_name='Rol')),
                ('institution', models.CharField(blank=True, max_length=255, verbose_name='Kurum')),
                ('orcid', models.CharField(blank=True, help_text='ORCID kimliği (örn: 0000-0002-1234-5678)', max_length=50, verbose_name='ORCID ID')),
                ('research_purpose', models.TextField(blank=True, help_text='Korpusu neden kullanmak istiyorsunuz?', verbose_name='Araştırma Amacı')),
                ('verification_status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=20, verbose_name='Doğrulama Durumu')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Doğrulama Tarihi')),
                ('api_key', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='API Anahtarı')),
                ('api_quota_daily', models.IntegerField(default=1000, verbose_name='Günlük API Kotası')),
                ('api_calls_today', models.IntegerField(default=0, verbose_name='Bugünkü API Çağrıları')),
                ('api_last_reset', models.DateField(auto_now_add=True, verbose_name='API Sayacı Sıfırlama')),
                ('export_quota_mb', models.IntegerField(default=5, help_text='Registered: 5MB, Verified: 100MB', verbose_name='Aylık Export Kotası (MB)')),
                ('export_used_mb', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Kullanılan Export (MB)')),
                ('export_last_reset', models.DateField(auto_now_add=True, verbose_name='Export Sayacı Sıfırlama')),
                ('queries_today', models.IntegerField(default=0, verbose_name='Bugünkü Sorgular')),
                ('query_last_reset', models.DateField(auto_now_add=True, verbose_name='Sorgu Sayacı Sıfırlama')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='Kullanım Koşulları Kabul Edildi')),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Koşulların Kabul Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_users', to=settings.AUTH_USER_MODEL, verbose_name='Doğrulayan Admin')),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
