# Generated by Django 5.0 on 2026-02-08 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0009_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('export_type', models.CharField(choices=[('concordance', 'Konkordans'), ('frequency', 'Frekans Listesi'), ('document', 'Tam Doküman'), ('analysis', 'Analiz Sonuçları'), ('statistics', 'İstatistikler')], max_length=20, verbose_name='Export Tipi')),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON'), ('conllu', 'CoNLL-U'), ('txt', 'Text'), ('xlsx', 'Excel'), ('pdf', 'PDF')], max_length=10, verbose_name='Format')),
                ('query_text', models.TextField(blank=True, help_text='Query that generated the exported data', verbose_name='İlgili Sorgu')),
                ('row_count', models.IntegerField(default=0, help_text='Number of rows/records exported', verbose_name='Satır Sayısı')),
                ('file_size_bytes', models.BigIntegerField(default=0, verbose_name='Dosya Boyutu (byte)')),
                ('file_size_mb', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Dosya Boyutu (MB)')),
                ('watermark_applied', models.BooleanField(default=True, help_text='Whether export includes platform watermark', verbose_name='Filigran Eklendi')),
                ('citation_text', models.TextField(blank=True, help_text='Citation text included in export', verbose_name='Atıf Metni')),
                ('download_count', models.IntegerField(default=0, help_text='How many times file was downloaded', verbose_name='İndirme Sayısı')),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Son İndirme')),
                ('file_path', models.CharField(blank=True, help_text='Storage path for generated file', max_length=512, verbose_name='Dosya Yolu')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Export file auto-delete date (30 days default)', null=True, verbose_name='Geçerlilik Süresi')),
                ('quota_before_mb', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Önceki Kota (MB)')),
                ('quota_after_mb', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sonraki Kota (MB)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_logs', to='corpus.document', verbose_name='Doküman')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_logs', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Export Logu',
                'verbose_name_plural': 'Export Logları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='corpus_expo_user_id_684884_idx'), models.Index(fields=['export_type', 'format'], name='corpus_expo_export__02c65d_idx'), models.Index(fields=['-created_at'], name='corpus_expo_created_9bd4c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Django session key for anonymous user tracking', max_length=40, null=True, verbose_name='Oturum Anahtarı')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.CharField(blank=True, max_length=256, verbose_name='User Agent')),
                ('query_text', models.TextField(verbose_name='Sorgu Metni')),
                ('query_type', models.CharField(choices=[('word', 'Kelime'), ('lemma', 'Kök'), ('pos', 'POS Tag'), ('advanced', 'Gelişmiş'), ('concordance', 'Konkordans'), ('frequency', 'Frekans'), ('ngram', 'N-gram')], max_length=20, verbose_name='Sorgu Tipi')),
                ('filters_applied', models.JSONField(blank=True, default=dict, help_text='Case sensitivity, regex, context size, etc.', verbose_name='Uygulanan Filtreler')),
                ('result_count', models.IntegerField(default=0, verbose_name='Sonuç Sayısı')),
                ('execution_time_ms', models.IntegerField(blank=True, help_text='Query execution time in milliseconds', null=True, verbose_name='İşlem Süresi (ms)')),
                ('is_cached', models.BooleanField(default=False, help_text='Whether results were served from cache', verbose_name='Önbellekten')),
                ('rate_limit_hit', models.BooleanField(default=False, help_text='Query blocked due to rate limit', verbose_name='Limit Aşıldı')),
                ('daily_query_count', models.IntegerField(default=1, help_text="User's query count when this query was made", verbose_name='Günlük Sorgu Sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tarih')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_logs', to='corpus.document', verbose_name='Doküman')),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_logs', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Sorgu Logu',
                'verbose_name_plural': 'Sorgu Logları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='corpus_quer_user_id_a5f80c_idx'), models.Index(fields=['ip_address', '-created_at'], name='corpus_quer_ip_addr_c0179c_idx'), models.Index(fields=['query_type', '-created_at'], name='corpus_quer_query_t_958246_idx'), models.Index(fields=['-created_at'], name='corpus_quer_created_181810_idx')],
            },
        ),
    ]
