# Generated by Django 5.0 on 2026-02-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0010_exportlog_querylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='conllu_data',
            field=models.JSONField(blank=True, default=list, help_text='Bağımlılık ayrıştırma verileri (10 sütunlu CoNLL-U formatı)', null=True, verbose_name='CoNLL-U Verisi'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='dependency_parser',
            field=models.CharField(blank=True, default='', help_text="Kullanılan ayrıştırıcı (örn: 'stanza-tr', 'spaCy-tr')", max_length=100, verbose_name='Bağımlılık Ayrıştırıcı'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='has_dependencies',
            field=models.BooleanField(default=False, help_text='Bu belgenin bağımlılık ayrıştırma verisi var mı?', verbose_name='Bağımlılık Verisi Var'),
        ),
    ]
