# Generated by Django 5.0 on 2026-02-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0011_add_conllu_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='collection',
            field=models.CharField(blank=True, help_text='Alt küme kategorisi (örn: Modern Türk Edebiyatı, Basın Metinleri)', max_length=100, verbose_name='Koleksiyon'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_date',
            field=models.DateField(blank=True, help_text='Metnin gerçek oluşturulma tarihi (yükleme tarihinden farklı)', null=True, verbose_name='Belge Tarihi'),
        ),
        migrations.AddField(
            model_name='document',
            name='license',
            field=models.CharField(choices=[('public_domain', 'Kamu Malı'), ('cc_by', 'CC BY - İsim Belirtme'), ('cc_by_sa', 'CC BY-SA - Aynı Lisansla Paylaşım'), ('cc_by_nc', 'CC BY-NC - Ticari Olmayan'), ('cc_by_nc_sa', 'CC BY-NC-SA - Ticari Olmayan, Aynı Lisansla'), ('educational', 'Eğitim Amaçlı Kullanım'), ('copyright', 'Telif Hakkı Korumalı'), ('unknown', 'Bilinmiyor')], default='unknown', help_text='Belgenin kullanım lisansı', max_length=30, verbose_name='Lisans'),
        ),
        migrations.AddField(
            model_name='document',
            name='region',
            field=models.CharField(blank=True, help_text='Coğrafi köken (örn: İstanbul, Anadolu, Rumeli)', max_length=100, verbose_name='Bölge/Lehçe'),
        ),
        migrations.AddField(
            model_name='document',
            name='text_type',
            field=models.CharField(choices=[('written', 'Yazılı'), ('spoken', 'Sözlü'), ('mixed', 'Karma'), ('web', 'Web/Dijital')], default='written', help_text='Yazılı, sözlü veya karma metin', max_length=20, verbose_name='Metin Türü'),
        ),
        migrations.AddField(
            model_name='document',
            name='token_count',
            field=models.IntegerField(default=0, help_text='Otomatik hesaplanan kelime/token sayısı', verbose_name='Token Sayısı'),
        ),
    ]
