# Generated by Django 5.0 on 2026-02-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0012_add_corpus_metadata_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='anonymization_report',
            field=models.JSONField(blank=True, default=dict, help_text='Maskelenen varlıkların detayları (PERSON: 5, EMAIL: 2, vb.)', verbose_name='Anonimleştirme Raporu'),
        ),
        migrations.AddField(
            model_name='document',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, help_text='Belgenin anonimleştirildiği tarih', null=True, verbose_name='Anonimleştirme Tarihi'),
        ),
        migrations.AddField(
            model_name='document',
            name='contains_personal_data',
            field=models.BooleanField(default=False, help_text='Belgede tespit edilen kişisel veri var mı?', verbose_name='Kişisel Veri İçeriyor'),
        ),
        migrations.AddField(
            model_name='document',
            name='privacy_status',
            field=models.CharField(choices=[('raw', 'Ham Veri (İşlenmemiş)'), ('anonymized', 'Anonimleştirilmiş'), ('pseudonymized', 'Sözde Anonimleştirilmiş'), ('public', 'Genel Kullanıma Açık')], default='raw', help_text='Belgenin anonimleştirme durumu', max_length=20, verbose_name='Gizlilik Durumu'),
        ),
    ]
