# Generated by Django 5.0 on 2026-02-09 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0013_add_privacy_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('grace_period', 'Bekleme Süresi'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], db_index=True, default='pending', max_length=20, verbose_name='Durum')),
                ('deletion_type', models.CharField(choices=[('full', 'Tam Silme'), ('anonymize', 'Anonimleştirme')], default='full', max_length=20, verbose_name='Silme Türü')),
                ('reason', models.TextField(blank=True, verbose_name='Sebep')),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Talep Tarihi')),
                ('grace_period_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Bekleme Süresi Bitişi')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='İşlenme Tarihi')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='İptal Tarihi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('documents_count', models.IntegerField(default=0, verbose_name='Doküman Sayısı')),
                ('queries_count', models.IntegerField(default=0, verbose_name='Sorgu Sayısı')),
                ('exports_count', models.IntegerField(default=0, verbose_name='Export Sayısı')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Hesap Silme Talebi',
                'verbose_name_plural': 'Hesap Silme Talepleri',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', '-requested_at'], name='corpus_acco_user_id_ee016a_idx'), models.Index(fields=['status', '-requested_at'], name='corpus_acco_status_131b55_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('data_processing', 'Veri İşleme'), ('marketing', 'Pazarlama İletişimi'), ('third_party', 'Üçüncü Taraf Paylaşımı'), ('analytics', 'Analitik/Çerezler'), ('terms', 'Kullanım Koşulları'), ('privacy_policy', 'Gizlilik Politikası')], db_index=True, max_length=50, verbose_name='İzin Türü')),
                ('consented', models.BooleanField(default=False, verbose_name='İzin Verdi')),
                ('consented_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='İzin Tarihi')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='İzin Geri Çekme Tarihi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User Agent')),
                ('policy_version', models.CharField(default='1.0', max_length=20, verbose_name='Politika Versiyonu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'İzin Kaydı',
                'verbose_name_plural': 'İzin Kayıtları',
                'ordering': ['-consented_at'],
                'indexes': [models.Index(fields=['user', 'consent_type', '-consented_at'], name='corpus_cons_user_id_abe03d_idx')],
                'unique_together': {('user', 'consent_type', 'policy_version')},
            },
        ),
        migrations.CreateModel(
            name='DataExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız'), ('expired', 'Süresi Doldu')], db_index=True, default='pending', max_length=20, verbose_name='Durum')),
                ('format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('both', 'Both (JSON + CSV)')], default='json', max_length=10, verbose_name='Format')),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Talep Tarihi')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='İşlenme Tarihi')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('json_file', models.FileField(blank=True, null=True, upload_to='data_exports/json/', verbose_name='JSON Dosyası')),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='data_exports/csv/', verbose_name='CSV Dosyası')),
                ('downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='İndirilme Tarihi')),
                ('download_count', models.IntegerField(default=0, verbose_name='İndirme Sayısı')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Geçerlilik Süresi')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata Mesajı')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_export_requests', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Veri İhraç Talebi',
                'verbose_name_plural': 'Veri İhraç Talepleri',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', '-requested_at'], name='corpus_data_user_id_761742_idx'), models.Index(fields=['status', '-requested_at'], name='corpus_data_status_745306_idx')],
            },
        ),
    ]
