# Generated by Django 5.0 on 2026-02-09 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0014_accountdeletionrequest_consentrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_format', models.CharField(choices=[('vrt', 'VRT (Corpus Workbench)'), ('conllu', 'CoNLL-U (Universal Dependencies)'), ('plain', 'Plain Text')], max_length=20, verbose_name='Kaynak Format')),
                ('global_metadata', models.JSONField(blank=True, default=dict, help_text='Document-level attributes (author, date, genre, etc.)', verbose_name='Global Metadata')),
                ('structural_annotations', models.JSONField(blank=True, default=dict, help_text='Paragraph, section, speaker information', verbose_name='Yapısal Anotasyonlar')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='İmport Tarihi')),
                ('original_filename', models.CharField(max_length=500, verbose_name='Orijinal Dosya Adı')),
                ('file_hash', models.CharField(help_text='Duplicate detection', max_length=64, unique=True, verbose_name='Dosya Hash (SHA256)')),
                ('sentence_count', models.IntegerField(default=0, verbose_name='Cümle Sayısı')),
                ('unique_lemmas', models.IntegerField(default=0, verbose_name='Benzersiz Lemma Sayısı')),
                ('unique_forms', models.IntegerField(default=0, verbose_name='Benzersiz Form Sayısı')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corpus_metadata', to='corpus.document', verbose_name='Belge')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='İmport Eden')),
            ],
            options={
                'verbose_name': 'Korpus Metadata',
                'verbose_name_plural': 'Korpus Metadata',
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(help_text="Belge içindeki sıra numarası (1'den başlar)", verbose_name='Cümle Sırası')),
                ('text', models.TextField(help_text='Ham metin formu', verbose_name='Cümle Metni')),
                ('token_count', models.IntegerField(default=0, verbose_name='Token Sayısı')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Sentence-level metadata (sent_id, text, etc.)', verbose_name='Metadata')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='corpus.document', verbose_name='Belge')),
            ],
            options={
                'verbose_name': 'Cümle',
                'verbose_name_plural': 'Cümleler',
                'ordering': ['document', 'index'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(help_text="Cümle içindeki pozisyon (1'den başlar)", verbose_name='Token Sırası')),
                ('form', models.CharField(db_index=True, help_text='Surface form (FORM in CoNLL-U)', max_length=255, verbose_name='Kelime Formu')),
                ('lemma', models.CharField(blank=True, db_index=True, help_text='Base form (LEMMA in CoNLL-U)', max_length=255, verbose_name='Lemma')),
                ('upos', models.CharField(blank=True, db_index=True, help_text='Universal POS tag (NOUN, VERB, etc.)', max_length=20, verbose_name='UPOS')),
                ('xpos', models.CharField(blank=True, help_text='Language-specific POS tag', max_length=50, verbose_name='XPOS')),
                ('feats', models.CharField(blank=True, help_text='Morphological features (Case=Nom|Number=Sing)', max_length=500, verbose_name='Morph Features')),
                ('head', models.IntegerField(blank=True, help_text='Head token index (0 for root)', null=True, verbose_name='Head')),
                ('deprel', models.CharField(blank=True, help_text='Syntactic relation to head (nsubj, obj, etc.)', max_length=50, verbose_name='Dependency Relation')),
                ('deps', models.CharField(blank=True, help_text='Enhanced dependency graph', max_length=500, verbose_name='Enhanced Dependencies')),
                ('misc', models.CharField(blank=True, help_text='Additional annotations (SpaceAfter=No, etc.)', max_length=500, verbose_name='Misc')),
                ('vrt_attributes', models.JSONField(blank=True, default=dict, help_text='Extra VRT tab-separated attributes', verbose_name='VRT Attributes')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='corpus.document', verbose_name='Belge')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='corpus.sentence', verbose_name='Cümle')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'ordering': ['document', 'sentence', 'index'],
            },
        ),
        migrations.AddIndex(
            model_name='sentence',
            index=models.Index(fields=['document', 'index'], name='corpus_sent_documen_e14d92_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['document', 'index'], name='corpus_toke_documen_5a6834_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['sentence', 'index'], name='corpus_toke_sentenc_ab8b58_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['form'], name='corpus_toke_form_f100f9_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['lemma'], name='corpus_toke_lemma_f9ccc5_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['upos'], name='corpus_toke_upos_e6e0e7_idx'),
        ),
    ]
