"""CWB (Corpus Workbench) integration bridge.

Provides tools for:
- Registry file generation
- VRT encoding to CWB format
- CQL query execution
"""
import subprocess
from pathlib import Path
from typing import Optional, Dict, Any, List
import logging

logger = logging.getLogger(__name__)


class CWBBridge:
    """Bridge to CWB (Corpus Workbench) for corpus indexing and querying."""
    
    def __init__(self, corpus_name: str, data_dir: str):
        """Initialize CWB bridge.
        
        Args:
            corpus_name: Corpus identifier (lowercase, no spaces)
            data_dir: Root directory for corpus data
        """
        self.corpus_name = corpus_name.lower()
        self.data_dir = Path(data_dir)
        self.corpus_dir = self.data_dir / self.corpus_name
        self.registry_dir = self.data_dir / "registry"
        
        # Create directories
        self.corpus_dir.mkdir(parents=True, exist_ok=True)
        self.registry_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_registry(self, metadata: Optional[Dict[str, Any]] = None) -> Path:
        """Generate CWB registry file.
        
        Args:
            metadata: Optional corpus metadata
        
        Returns:
            Path to registry file
        """
        metadata = metadata or {}
        
        registry_content = f"""##
## Registry entry for {self.corpus_name}
## Generated by OCRchestra
##

NAME {self.corpus_name}
ID   {self.corpus_name}
HOME {self.corpus_dir.absolute()}
INFO "{metadata.get('description', 'Turkish corpus from OCRchestra')}"

## Corpus properties
LANGUAGE "Turkish"
ENCODING "utf-8"

## Positional attributes (token-level)
ATTRIBUTE word
ATTRIBUTE lemma
ATTRIBUTE pos
ATTRIBUTE morph

## Structural attributes (document/sentence level)
STRUCTURE doc
STRUCTURE doc_id
STRUCTURE doc_filename
STRUCTURE doc_date
STRUCTURE doc_author
STRUCTURE doc_genre

STRUCTURE p
STRUCTURE p_id

STRUCTURE s
STRUCTURE s_id
"""
        
        registry_file = self.registry_dir / self.corpus_name
        with open(registry_file, 'w', encoding='utf-8') as f:
            f.write(registry_content)
        
        logger.info(f"Registry file created: {registry_file}")
        return registry_file
    
    def encode_vrt(self, vrt_file: Path, overwrite: bool = False) -> bool:
        """Encode VRT file to CWB binary format.
        
        Args:
            vrt_file: Path to VRT file
            overwrite: Overwrite existing corpus
        
        Returns:
            True if successful
        """
        if not vrt_file.exists():
            logger.error(f"VRT file not found: {vrt_file}")
            return False
        
        # Check if corpus already exists
        if (self.corpus_dir / "word.corpus").exists() and not overwrite:
            logger.warning(f"Corpus {self.corpus_name} already exists. Use overwrite=True.")
            return False
        
        # Build cwb-encode command
        cmd = [
            "cwb-encode",
            "-d", str(self.corpus_dir),
            "-f", str(vrt_file),
            "-R", str(self.registry_dir / self.corpus_name),
            "-x",  # XML mode
            "-s",  # Skip empty lines
            "-c", "utf8",  # Character encoding
            # Positional attributes
            "-P", "word",
            "-P", "lemma",
            "-P", "pos",
            "-P", "morph",
            # Structural attributes
            "-S", "doc:0+id+filename+date+author+genre",
            "-S", "p:0+id",
            "-S", "s:0+id",
        ]
        
        try:
            logger.info(f"Encoding VRT file: {vrt_file}")
            result = subprocess.run(cmd, capture_output=True, text=True, check=True)
            logger.info(f"CWB encode successful: {result.stdout}")
            return True
        
        except subprocess.CalledProcessError as e:
            logger.error(f"CWB encode failed: {e.stderr}")
            return False
        
        except FileNotFoundError:
            logger.error("cwb-encode not found. Is CWB installed?")
            return False
    
    def make_index(self) -> bool:
        """Create compressed indices (cwb-makeall).
        
        Returns:
            True if successful
        """
        cmd = [
            "cwb-makeall",
            "-r", str(self.registry_dir),
            self.corpus_name.upper(),
        ]
        
        try:
            logger.info(f"Creating indices for {self.corpus_name}")
            result = subprocess.run(cmd, capture_output=True, text=True, check=True)
            logger.info(f"Indexing successful: {result.stdout}")
            return True
        
        except subprocess.CalledProcessError as e:
            logger.error(f"Indexing failed: {e.stderr}")
            return False
        
        except FileNotFoundError:
            logger.error("cwb-makeall not found. Is CWB installed?")
            return False
    
    def query_cql(self, cql_query: str, max_results: int = 100) -> List[str]:
        """Execute CQL query via CQP.
        
        Args:
            cql_query: CQL query string
            max_results: Maximum number of results
        
        Returns:
            List of concordance lines
        """
        # CQP commands
        cqp_input = f"""
        set Registry "{self.registry_dir}";
        {self.corpus_name.upper()};
        set LeftContext 10;
        set RightContext 10;
        {cql_query};
        cat Last {max_results};
        exit;
        """
        
        try:
            result = subprocess.run(
                ["cqp", "-c"],
                input=cqp_input,
                capture_output=True,
                text=True,
                check=True
            )
            
            lines = result.stdout.strip().split('\n')
            return lines
        
        except subprocess.CalledProcessError as e:
            logger.error(f"CQP query failed: {e.stderr}")
            return []
        
        except FileNotFoundError:
            logger.error("cqp not found. Is CWB installed?")
            return []
    
    def corpus_info(self) -> Dict[str, Any]:
        """Get corpus information.
        
        Returns:
            Dictionary with corpus stats
        """
        cmd = [
            "cwb-describe-corpus",
            "-r", str(self.registry_dir),
            self.corpus_name.upper(),
        ]
        
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, check=True)
            
            # Parse output (simple)
            info = {
                "name": self.corpus_name,
                "status": "indexed",
                "output": result.stdout
            }
            
            return info
        
        except subprocess.CalledProcessError as e:
            logger.error(f"Corpus info failed: {e.stderr}")
            return {"name": self.corpus_name, "status": "error", "error": str(e)}
        
        except FileNotFoundError:
            logger.error("cwb-describe-corpus not found.")
            return {"name": self.corpus_name, "status": "cwb_not_installed"}
