# Generated by Django 5.0 on 2026-02-08 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this API key', max_length=100)),
                ('key', models.CharField(editable=False, max_length=64, unique=True)),
                ('tier', models.CharField(choices=[('free', 'Free (1000 requests/day)'), ('standard', 'Standard (10,000 requests/day)'), ('premium', 'Premium (100,000 requests/day)'), ('unlimited', 'Unlimited')], default='free', max_length=20)),
                ('requests_today', models.IntegerField(default=0)),
                ('last_request', models.DateTimeField(blank=True, null=True)),
                ('total_requests', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('allowed_ips', models.TextField(blank=True, help_text='Comma-separated IP addresses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
